### ISSUE TITLE
Error in running the app : the map are not displayed

### ISSUE THREAD

**Issue by LauraHenckel** [AlejandroRuete/IgnoranceMaps#2]
Thanks a lot for this app! However, I can't see the maps. The application launches but I get the error message displayed under the map tab: "error: the condition has length > 1". In addition, the following message is displayed in the R console: 
Warning: shapelib support is provided by GDAL through the sf and terra packages among others
Warning: Error in if: the condition has length > 1
   173: .rasterImagePlot
   172: .plotraster2
   171: .local
   170: pad
   168: renderPlot [C:\Users\User\Desktop\IgnoranceMaps-master\SLWapp/server.R#307]
   166: func
   126: drawPlot
   112: <reactive:plotObj>
    96: drawReactive
    83: renderFunc
    82: output$ObsPlot
     1: runApp         Does it come from old packages that are no longer supported?

**Comment by aleruete** [comment]
Thank you for the report. This app has not been updated for quite a long time. As you say, the problem is most likely a broken package dependency. You can still use the same algorithms in an updated version of this here [Species observation explorer](https://greensway.se/tjanster/digital-plattform/species-observations-explorer/species-observations-explorer-lite/)
